title: "Ingenieria de Datos"
author: "Sebastian Ruiz Martinez"
description: "Ingenieria de Datos"
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: "home", sidebaricon: "home"}
  - {file: "README.md" , icon: "book", sidebaricon: "book"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/niklasbuschmann/contrast"}
  - {title: LinkedIn, icon: linkedin, url: "https://www.linkedin.com/in/sebastianruizmartinez"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
